### PR TITLE
Schema v10 update

### PR DESCRIPTION
**Pull request by mallardduck**
This PR is purely a schema update patch that uses the newest Schema source that the generator can handle.
Unfortunately this is just a single version bump and the newest is v13 - so that's why #165 is laying foundation for newer data sources.

However I figured this could be created quickly and easily, so I may as well submit a PR to the current master as well. This way a release based on a slightly newer schema could be published if desired. Aside from a few additions, most changes seem to be fixes for URLs in docblocks to use HTTPS.

### CODE REVIEW

**Review by Gummibeer — APPROVED** [review]
Thanks! 🎉
And yes, single version bumps are always preferred. As it allows people to go to the version they want/need.

**Comment by mallardduck** [comment]
> single version bumps are always preferred

Perfect - I will follow up with PRs for each incrementing schema version. There's going to be a lot of new tagged releases for people to get those options. 😄

**Comment by Gummibeer** [comment]
I will release the first one in few minutes. Only have to find time for the changelog and release. 😂

**Comment by mallardduck** [comment]
Sounds good - hopefully my PR #168 helps with changelog stuff.

If you would like me to get more explicit with changes we could - but people should probably mostly refer to the SchemaOrg change-logs. 😉

**Comment by Gummibeer** [comment]
https://github.com/spatie/schema-org/releases/tag/3.5.0

**Pull request merged**
