### PR TITLE
generate types 2020-01-20

### PR DESCRIPTION
**Pull request by Gummibeer**

### CODE REVIEW

**Comment by Gummibeer** [comment]
@sebastiandedeyne should we release this as a minor version or because of the changed types to enum as a BC major one? So far I know we've always released the schema.rdfa changes as minor ones because we have no control there and it would be a massive task to check everytime if something would break.

**Comment by sebastiandedeyne** [comment]
I'm pretty sure a minor version is okay.

I don't think regenerating the schema can ever break anything, since `BaseType` has a `__call` method to catch everything.

https://github.com/spatie/schema-org/blob/d44026cdf6fa874b64290d8267cb7acd6a613652/src/BaseType.php#L139-L142

The only thing that can "break" is autocompletion if a method property disappears (if Schema.org ever even does that), but it will never cause a runtime error.

**Comment by Gummibeer** [comment]
@sebastiandedeyne you are right. Only the autocompletion will "break". Will release this. :)

**Comment by Gummibeer** [comment]
https://github.com/spatie/schema-org/releases/tag/2.12.0

**Pull request merged**
