### PR TITLE
Allow to set different context for graph

### PR DESCRIPTION
**Pull request by Toflar**
Hey there,

Excellent library! I enjoy working with it a lot.
I have a similar use case as described in https://github.com/spatie/schema-org/issues/25. I managed to write my own types by just extending `BaseType` which is enough for my use case because there's not many. However, I cannot use the `Graph` class for my own context right now which this simple PR would solve :)

### CODE REVIEW

**Comment by Gummibeer** [comment]
Hey,
I just wonder why extending the `Graph` class like the `BaseType` isn't a solution? 🤔

I think that this `setContext()` method could lead to more issues than it solves as you can change the context on runtime.

So a `BibGraph` or `HealthLifesciGraph` would be more explicit than changing the graph context on runtime.

I'm not fully against that PR but right now I think that custom graphs are a better solution.

**Comment by Toflar** [comment]
That's what I did as a workaround. What I wanted to build was a schema manager for arbitrary schemas along the lines of:

```php
public function getGraphForSchema(string $schema): Graph
{
    if (!\array_key_exists($schema, $this->graphs)) {
        $this->graphs[$schema] = (new Graph())->setSchema($schema));
    }

    return $this->graphs[$schema];
}
```

That way it'd be dynamic. Otherwise I have to build some extension point where third party developers can register their own factories for their own schemas so that other custom schemas become possible.

I agree that "changing the context at runtime" shouldn't be possible though. What if we just make it a constructor argument without any setter?

**Comment by Gummibeer** [comment]
Okay, thanks for explaining your case.

In the context of Laravel/Symfony I would use the container to manage graph instances and use their FQCN as an identifier.
But these would be framework-specific implementations and a plain PHP one would be cool.

The optional construct argument seems like a good solution. With PHP8 we have named arguments so even if we should get more in the future the user can skip the context - but I would still prefer a `?string` type - so default applied via `?? $default`.

**Comment by Toflar** [comment]
Of course I'd use a DIC container for that but I still think it's a bit overengineered to provide factories etc. just for that one context :) I'll update the PR soon.

**Comment by Toflar** [comment]
PR updated, was that your preferred variant?
BTW: Thanks for being so constructive on that topic <3

**Review by Gummibeer — APPROVED** [review]

**Comment by Gummibeer** [comment]
https://github.com/spatie/schema-org/releases/tag/3.4.0

**Pull request merged**
