### PR TITLE
Extensible generator (resolves #25)

### LINKED ISSUE #25: Make generator extensible for other Schema definitions
Not so much an issue, just a question.

I'd love to use this package but without the health-lifesci.schema.org extension I might need to roll my own.  Is there a way for me to add schema extensions so I can benefit from using the MedicalOrganization type "Physician"?  

Is it possible to somehow run your generator against that health-lifesci schema extension and generate a library of files in my project to augment your core files?

### PR DESCRIPTION
**Pull request by greatislander**
This PR adds an `--extensions` flag to the `generate` command which accepts a comma-separated list of any or all of the following Schema.org extensions:

- `auto`
- `bib`
- `health-lifesci`

It also modifies the `Definitions` class, the `DefinitionParser` class, and the `ParseType` class to handle multiple input sources and extension types which have a `schema:` prefix as mentioned in [this comment](https://github.com/spatie/schema-org/issues/25#issuecomment-357271591) on the original issue. I've confirmed that running the command produces the expected supplementary classes.

Please let me know if there's anything I can add to the PR to improve it in terms of code quality or tests. And thanks for considering my contribution!

### CODE REVIEW

**Comment by Gummibeer** [comment]
**git status --porcelain**
```
 M src/AllocateAction.php
 M src/Car.php
 M src/CreativeWork.php
 M src/EngineSpecification.php
 M src/ExerciseAction.php
 M src/Hospital.php
 M src/MedicalOrganization.php
 M src/PayAction.php
 M src/PeopleAudience.php
 M src/Physician.php
 M src/Schema.php
 M src/Vehicle.php
?? src/AnatomicalStructure.php
?? src/AnatomicalSystem.php
?? src/ApprovedIndication.php
?? src/Artery.php
?? src/Atlas.php
?? src/Audiobook.php
?? src/BloodTest.php
?? src/Bone.php
?? src/BrainStructure.php
?? src/BusOrCoach.php
?? src/CarUsageType.php
?? src/Chapter.php
?? src/Collection.php
?? src/DDxElement.php
?? src/DiagnosticLab.php
?? src/DiagnosticProcedure.php
?? src/Diet.php
?? src/DietarySupplement.php
?? src/DoseSchedule.php
?? src/Drug.php
?? src/DrugClass.php
?? src/DrugCost.php
?? src/DrugCostCategory.php
?? src/DrugLegalStatus.php
?? src/DrugPregnancyCategory.php
?? src/DrugPrescriptionStatus.php
?? src/DrugStrength.php
?? src/ExercisePlan.php
?? src/ImagingTest.php
?? src/InfectiousAgentClass.php
?? src/InfectiousDisease.php
?? src/Joint.php
?? src/LifestyleModification.php
?? src/Ligament.php
?? src/LymphaticVessel.php
?? src/MaximumDoseSchedule.php
?? src/MedicalAudience.php
?? src/MedicalBusiness.php
?? src/MedicalCause.php
?? src/MedicalClinic.php
?? src/MedicalCode.php
?? src/MedicalCondition.php
?? src/MedicalConditionStage.php
?? src/MedicalContraindication.php
?? src/MedicalDevice.php
?? src/MedicalDevicePurpose.php
?? src/MedicalEntity.php
?? src/MedicalEnumeration.php
?? src/MedicalEvidenceLevel.php
?? src/MedicalGuideline.php
?? src/MedicalGuidelineContraindication.php
?? src/MedicalGuidelineRecommendation.php
?? src/MedicalImagingTechnique.php
?? src/MedicalIndication.php
?? src/MedicalIntangible.php
?? src/MedicalObservationalStudy.php
?? src/MedicalObservationalStudyDesign.php
?? src/MedicalProcedure.php
?? src/MedicalProcedureType.php
?? src/MedicalRiskCalculator.php
?? src/MedicalRiskEstimator.php
?? src/MedicalRiskFactor.php
?? src/MedicalRiskScore.php
?? src/MedicalScholarlyArticle.php
?? src/MedicalSign.php
?? src/MedicalSignOrSymptom.php
?? src/MedicalSpecialty.php
?? src/MedicalStudy.php
?? src/MedicalStudyStatus.php
?? src/MedicalSymptom.php
?? src/MedicalTest.php
?? src/MedicalTestPanel.php
?? src/MedicalTherapy.php
?? src/MedicalTrial.php
?? src/MedicalTrialDesign.php
?? src/MedicalWebPage.php
?? src/MedicineSystem.php
?? src/Motorcycle.php
?? src/MotorizedBicycle.php
?? src/Muscle.php
?? src/Nerve.php
?? src/Newspaper.php
?? src/OccupationalTherapy.php
?? src/Optician.php
?? src/PalliativeProcedure.php
?? src/PathologyTest.php
?? src/Patient.php
?? src/PhysicalActivity.php
?? src/PhysicalActivityCategory.php
?? src/PhysicalExam.php
?? src/PhysicalTherapy.php
?? src/PreventionIndication.php
?? src/PsychologicalTreatment.php
?? src/RadiationTherapy.php
?? src/RecommendedDoseSchedule.php
?? src/ReportedDoseSchedule.php
?? src/Substance.php
?? src/SuperficialAnatomy.php
?? src/SurgicalProcedure.php
?? src/TherapeuticProcedure.php
?? src/Thesis.php
?? src/TreatmentIndication.php
?? src/Vein.php
?? src/Vessel.php
?? src/VeterinaryCare.php
?? src/VitalSign.php
```

**Comment by Gummibeer** [comment]
Great work but I have some ideas/suggestions.
* Symfony commands allow to use the same option multiple times and it will create an array out of it - replaces the `explode()`.
* how about special options, without value, foreach official extension `--auto`, `--bib`, `--health` or something like compiling php `--with-auto` and so on. And a dynamic `--source=` option to allow the user to add every rdfa schema extension.

**Comment by Gummibeer** [comment]
@freekmurze & @sebastiandedeyne - this isn't done. Can you please reopen this one?

**Comment by greatislander** [comment]
Sorry for the inaction on this! I was a bit swamped at the end of the year. Hoping to get back at this soon.

**Comment by Gummibeer** [comment]
poke @spatie @sebastiandedeyne 
If no one has time to do the requested changes I would offer to do it but don't want to do it twice.

**Comment by sebastiandedeyne** [comment]
Time for me to be realistic, I really don't have time to maintain these features at the moment... @Gummibeer my colleagues say you're doing great work on our other packages, would you be interested in becoming a maintainer of this one too?

**Comment by Gummibeer** [comment]
@sebastiandedeyne Because it's not this busy here I will try my best to help you! :)

**Comment by sebastiandedeyne** [comment]
Thank you! I invited you as a collaberator :)

**Comment by Gummibeer** [comment]
I will start to work on this base in `spatie:extensible-generator` branch. @greatislander thanks for your work so far!

**Pull request merged**
