### PR TITLE
Convert Default Context to https

### PR DESCRIPTION
**Pull request by dougblackjr**
Addresses #60. Converts base type default context to https.

Most of schema.org still points to `http://schema.org`, so I'm not totally sure the protocol on this. However, the site defaults to https now.

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Perfect, thanks!

**Comment by icedevelopment** [comment]
It seems like all the constants are still using http instead of https for example ItemAvailability::OutOfStock.

**Comment by Gummibeer** [comment]
@icedevelopment this is caused by the schema RDFA file https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/schema.rdfa which uses `http` for everything. I would say that they do this to don't introduce a BC.
And because these values are used by the readers I wouldn't recommend to change them.

**Comment by icedevelopment** [comment]
Ok I see. Thanks for the quick reply.

**Pull request merged**
